/*
Script to import accountNames from mucu data excel sheet.
*/

start transaction ;
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ACHAR PETER ODHIAMBO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ALFRED JOEL',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ANGELA JEPTANUI YEGO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ANGELAH JEPKEMBOI SAWE',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ANN NDANU WAMBUA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ANNET MBURU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ANTONY KAREU MATIBA NGATIA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ANTONY NJOGU WAITATHU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ATANAS KIZITUS MZEE',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('BARBARA AKELO OSIRO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('BEATRICE NJUHI NJENGA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('BELCHA AGESA SABWA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('BELINDAH MUTUMI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('BENEDICT MUSYOKA MUTUKU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('BENJAMIN /NELLY KIVUVA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('BENSON KISINI MULI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('BENSON MACHARIA MAINA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('BERNARD KIPKEMOI NGENO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('BETHWEL KIPCHIRCHIR KEMEI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('BILLY SIMANI SIMWA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('BOAZ / FANCY LAGAT',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('BORNACE KIMELI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('CALEB KAGERA DAVID',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('CARLPETERS ETHALIE MBAABU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('CAROLINE OWANO OKILA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('CAROLINE ROTICH',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('CAROLINE WANGUI NG\'ANG\'A',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('CAROLINE WANJIKU MUNGE',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('CHARLES CHEGE IRUNGU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('CHRISTOPHER KAUME',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('CYNTHIA / BRIAN ANYIRA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('DANIEL KIMOTHO MWANZIA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('DAVID MURAGURI MURIUKI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('DAVIS/MERCY MUGUIMI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('DEBORA ORESIA D\'SUTSA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('DENNIS KIMEU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('DIANA W WANJIRU NJOGU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('DORCAS WAMBUI KIMANI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('DOREEN GATWIRI ',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('DORESE /ALPHONCE JUMA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('DUNCAN JUMA SIMIYU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('EDDAH MWIHAKI MURUNGI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('EDDAH WAHITO MUNYI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('EDITH MUIRI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('EDITH WANJIRU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('EDWIN  /BETTY CHESIRE',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('EDWIN SHIVO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ELIAS/CHRISTINE OGALO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ELIJAH MUTHEE JAPHET',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ELOSE MUTHONI MATHENGE',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('EMMAH WAMBUI NJOROGE',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('EPHANTUS W KANGARA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('EPHRAIM NJURE GIATHI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ERIC GITAU WANGUI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ERIC /JEMIMA NZOLA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ESTHER WAKOIMBI GUANDARU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ESTHER WANJIRU NDIRANGU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('FELIX SUMBA ',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('FINLAY MAINA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('FLORENCE KAGEHA ATICHI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('FLORENCE WAITHAKA/ JIMMY  MUTUA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('FRANCIS/JACKLINE GACOKI ',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('FRANK MATHEAH',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('FREDRICK ONYANGO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('GEOFFREY KAMAU  GIKONYO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('GEORGE NJENGA KINGORI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('GEORGE OWOUCHE',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('GICHIRA M MAINA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('GLORIA BETH MUTHONI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('HERMAN MURIIRA KIREA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('HILARY KIPRONO SACHIDA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('HICKS WASWA /FLORENCE AJIAMBO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('HILLARY NGUGI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('HILDA SICHANGI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('IRENE MUGUTHU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('IRENE WANGARI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JACKLINE CHEPKEMOI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JACKLINE MUTHONI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JACKLINE NDERITU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JACKSON VUSAKA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JACQUELINE ADHIAMBO OKOTH',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JAMES IRUNGU MWAI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JAMES MAINA / BAHATI MAWONDO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JAMES MURIITHI GACHOKI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JAMES ODAYA WESONGA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JAMES THIONG\'O IRUNGU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JANE W MWANGI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JANE WACHERA KANYARI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JANE WAMBOI WAINAINA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JARED MARWA MWIKWABE',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JARED S OKOTH MAK\'OBONYO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JEREMIAH / CATHERINE MATONDA ',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JIMMY  / EDITH GOR',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JOB /LUCY MUGO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JOB MUSAMALI SISUNGO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JOE KIMANI/JOAN KAWIRA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JOHN MAINGI MACHARIA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JOHN/ABIGAEL MACHECHE ',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JOHN WILLIS PESA AKACH',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JONAH / PAMELA KIROGO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JORAM MURIMI MURIUKI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JOSEPH MWANGI KAMAU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JOSHUA WANJOHI WANJOHI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JULIA WAMBUI NJENGA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('JUSTINA MUENI NGUGI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('KANUU MERCY JOHN/ DAVID BARASA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('KENNEDY MARURI KARANJA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('KENNEDY OTIENO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('KENNEDY OWINO OGUTU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('KIPROTICH NICHOLAS',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('LAURYN MWENDE KITHUKU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('LENCER AWUOR OKUMU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('LILIAN NABWAMI OJIAMBO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('LINDA MUDOLA DIODIO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('LOICE MURIITHI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('LYDIA WAWIRA KABURI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('LYDIAH KARAUKI MUTUURA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MANASES  MURREY/ DIANA KENDAGOR',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MARGARET  KURUMBU/EBENEZER GITHUTHA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MARTHA GATHERU NDERITU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MARTHA KARIUKI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MARTIN KUNGU KUNGU KIBIRO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MARY NZEMBI NZIOKA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MARY WANGARI KINUTHIA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MATTHEW MUGO NDONGU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MAURYNE MUKAMI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MAXINE CHEPTEEK KIBAS',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MERCY KARAMBU MARANGU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MERCY LUSWETI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MICHAEL KAMULU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MIRIAM NGILE MAWEU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MOFFAT NDARU NJERU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MONICAH / DENNIS MWANZIA ',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MONICAH WANGU WANJAU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MOSES KARANJA KARIUKI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MOSES NJENGA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('MUTAHE KARUORO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('NANCY WANJIKU KARUA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('NASHON TADO ',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('NATHAN WASIMELA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('NDUNGI KYALO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('NYANUMBA EVERLINE KWAMBOKA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('OKELLO DAVID SIMEON',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES (' LAMECK / JOYCE KAYALO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('PATRICK/MIRIAM MULINGE',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('PATRICK NG\'ANG\'A/ AGNES WACEKE',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('PATRICK OMOGA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('PAUL KAMAU ',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('PAUL  / DOREEN LEMALEE',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('PAULINE WAMBUI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('PENINA IRIMA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('PENINAH NGONDI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('PETER IRUNGU MURIGI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('POLYNE KANGAI NYAMU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('PRISCA CHERUIYOT/ISACK KIMAIYO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('RAYNOR/ ISAAC POLO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ROSE MUMBUA WAMBUA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('RUTH GACENGECI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('SAMUEL KIPRONNOH KISANG',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('SAMUEL MBWAYO MBWAYO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('SAMUEL / JUDY EMMA MUTIA ',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('SAMUEL NJUGUNA KIMANI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('SCARMEDA NYANG\'AU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('SHIRLEY MUNEE NALIFUMA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('SIMON K MUKUNDI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('SOLOMON MUTUA',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('STEPHEN/ROSEMARY JUMBALE',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('SUSAN MWANGI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('SYLVIA NASOMBI LONGOINO',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('TIMOTHY KEMBOI KIBARBET',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('TIMOTHY MBAU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('VICTORIA AKOTH OKUMU',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('VINCENT KIMOSOP',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('WINFRED MUTHONI',now(),now(),'');
INSERT INTO accounts(account_name,created_at,updated_at, deleted_at) VALUES ('ZIPPORAH WACHUKA NJUGUNA',now(),now(),'');
commit ;
