INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (1, 'user_management_access', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (2, 'permission_create', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (3, 'permission_edit', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (4, 'permission_show', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (5, 'permission_delete', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (6, 'permission_access', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (7, 'role_create', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (8, 'role_edit', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (9, 'role_show', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (10, 'role_delete', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (11, 'role_access', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (12, 'user_create', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (13, 'user_edit', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (14, 'user_show', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (15, 'user_delete', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (16, 'user_access', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (17, 'account_create', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (18, 'account_edit', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (19, 'account_show', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (20, 'account_delete', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (21, 'account_access', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (22, 'payment_create', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (23, 'payment_edit', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (24, 'payment_show', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (25, 'payment_delete', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (26, 'payment_access', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (27, 'profile_password_edit', null, null, null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (28, 'minute_access', '2021-02-19 19:37:44', '2021-02-19 19:37:44', null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (29, 'minute_create', '2021-02-19 19:37:56', '2021-02-19 19:37:56', null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (30, 'minute_edit', '2021-02-19 19:38:04', '2021-02-19 19:38:04', null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (31, 'minute_show', '2021-02-19 19:38:11', '2021-02-19 19:38:11', null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (32, 'minute_delete', '2021-02-19 19:38:27', '2021-02-19 19:38:27', null);
INSERT INTO mucu_db.permissions (id, title, created_at, updated_at, deleted_at) VALUES (33, 'my_account', '2021-02-24 18:52:40', '2021-02-24 18:52:40', null);